detection_and_tracking_test_node:

   display_main_window_mode: True
   record_main_window_mode: True

   display_top_view_window_mode: False
   record_top_view_window_mode: False

   print_time_stamp_mode: False
   print_xx_mode: False

   display_mask_mode: False
   display_pointcloud_mode: False
   display_result_mode: True

   image_topic: /usb_cam/image_rect_color
   lidar_topic: /pandar_points_processed
   pub_topic: /targets

   calibration_file_path: /home/lishangjie/shangjie/detection_and_tracking_ws/src/detection_and_tracking_test/conf/head_camera.yaml

   top_k_person: 6
   top_k_vehicle: 8
   score_threshold_person: 0.15
   score_threshold_vehicle: 0.65

   distance_limit: 100
   frame_rate: 10
   associate_threshold_person: 2
   associate_threshold_vehicle: 4
   max_tracking_times: 5
   sigmaax: 0.1
   sigmaay: 0.1
   sigmaox: 0.01
   sigmaoy: 0.01

   jet_color: 5
